name: Tests Terraform

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'Confirmation to apply Terraform changes'
        required: true
        default: 'no'
  push:
    branches:
      - main

jobs:
  Terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Azure login
        run: az login
        
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.6.4

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan
        
      - name: Confirm Apply
        run: |
          if [ "${{ github.event.inputs.confirmation }}" != "yes" ]; then
            echo "Terraform apply aborted."
            exit 1
          fi
          
      - name: Terraform Apply
        run: terraform apply
