name: Tests Terraform

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  Terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Azure login
        run : az login
        
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.6.4

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan
        
      - name: Manual Approval
        run: |
          if [ "$GITHUB_EVENT_NAME" == "push" ]; then
            echo "Manually approve the deployment on the GitHub Actions UI"
            exit 1
          fi

      - name: Terraform Apply
        run: terraform apply
